---
jobs:

- name: build-docker
  plan:
  - get: dockerfile-repo
    trigger: true
  - put: ci-docker-image
    params:
      build: dockerfile-repo/ci

- name: deploy-spring-music
  public: true
  serial: true
  plan:
    - get: ci-docker-image
      passed: [ build-docker ]
      trigger: true
    - get: spring-music
      trigger: true
    - task: build-spring-music
      config:
        platform: linux
        image: "docker:///jshah/java-pipeline"
        inputs:
        - name: spring-music
        run:
          path: bash
          args: [ "-c", "export TERM=linux; cd spring-music; ./gradlew assemble --info; cp ./build/libs/spring-music.war . " ]
    - put: deploy-web-app
      params:
        manifest: spring-music/manifest.yml


resources:

- name: ci-docker-image
  type: docker-image
  source:
    repository: jshah/java-pipeline
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: dockerfile-repo
  type: git
  source:
    paths: [ "ci/Dockerfile" ]
    branch: master
    uri: https://github.com/jshah-pivotal/spring-music.git

- name: spring-music
  type: git
  source:
    branch: master
    uri: https://github.com/jshah-pivotal/spring-music.git

- name: deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false
